name: okoul_movies_app
description: Movies Listing App For A Challenge at okoul.com

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  carousel_slider: ^4.2.1
  connectivity_plus: ^4.0.1
  dartz: ^0.10.1
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  freezed_annotation: ^2.2.0
  go_router: ^9.0.3
  google_fonts: ^5.1.0
  hooks_riverpod: ^2.3.6
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.2.0
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true
