name: cineverse
description: "Movies App"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  dio: 5.4.3
  flutter:
    sdk: flutter
  url_launcher: 6.2.6

dev_dependencies:
  flutter_lints: 4.0.0

flutter:
  uses-material-design: true
