name: okoul_movies_app
description: Movies Listing App For A Challenge at okoul.com

version: 1.0.1

environment:
  sdk: 3.1.5
  flutter: 3.13.9

dependencies:
  carousel_slider: ^4.2.1
  connectivity_plus: ^4.0.2
  dartz: ^0.10.1
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  freezed_annotation: ^2.4.1
  go_router: ^10.1.2
  google_fonts: ^5.1.0
  hooks_riverpod: ^2.3.10
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.4
  shared_preferences: ^2.2.0
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.3
  freezed: ^2.4.2
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.1

flutter:
  uses-material-design: true
