name: movies_app_okoul
description: Movies App Okoul

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  carousel_slider: ^4.2.1
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  font_awesome_flutter: ^10.3.0
  freezed_annotation: ^2.2.0
  go_router: ^5.2.4
  google_fonts: ^3.0.1
  hooks_riverpod: ^2.1.1
  json_annotation: ^4.7.0
  riverpod_annotation: ^1.0.6
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  riverpod_generator: ^1.0.6

flutter:
  uses-material-design: true
