name: movies_app_okoul
description: Movies App Okoul

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  # Sdk
  flutter:
    sdk: flutter
  # Ui
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.3.0
  google_fonts: ^3.0.1

  # Network
  connectivity_plus: ^3.0.2
  dio: ^4.0.6

  # Error Handling
  dartz: ^0.10.1

  # State Management
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1
  riverpod_annotation: ^1.0.6

  # Data Modeling
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

  # Navigation
  go_router: ^5.2.4

  # Storage and Cache
  shared_preferences: ^2.0.15

dev_dependencies:
  # Sdk
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  # Code Generation
  freezed: ^2.3.2
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  riverpod_generator: ^1.0.6

flutter:
  uses-material-design: true
